### ISSUE TITLE
Can we make it such that it works just exactly as the @vite() decorator

### ISSUE THREAD

**Issue by zaghadon** [motomedialab/laravel-vite-helper#11]
I mean in terms of the vite() helper working exactly as the @vite() blade decorator, in that it could accept array of resource paths and read the manifest to generate other resource URLs wherever necessary. 

Probably copy the @vite() decorator implementation if it's open source, which I believe it'll be.

**Comment by chrispage1** [comment]
Hi! The intention of this package is to provide an absolute URL to the asset without being opinionated on the code block surrounding it. Is there a particular use case you have for this?

Chris.

**Comment by kirkbushell** [comment]
If this worked exactly like the @vite decorator, it would fail to solve the main problem - being able to load vite assets on the backend.

**Comment by chrispage1** [comment]
> If this worked exactly like the @Vite decorator, it would fail to solve the main problem - being able to load vite assets on the backend.

Exactly and this functions differently giving you access to the URL rather than the surrounding tags, much like Laravel's old `mix` helper. I did try and PR this to Laravel core but it got rejected.

**Comment by chrispage1** [comment]
> I mean in terms of the vite() helper working exactly as the @Vite() blade decorator, in that it could accept array of resource paths and read the manifest to generate other resource URLs wherever necessary.
> 
> Probably copy the @Vite() decorator implementation if it's open source, which I believe it'll be.

Is it just the ability to get an array of URLs you are looking for @zaghadon ?

**Comment by zaghadon** [comment]
Yes, it was just an enhancement I decided to suggest. 

Such that I can simply call vite(['app','resource','bla']).

**Comment by chrispage1** [comment]
> Yes, it was just an enhancement I decided to suggest.
> 
> Such that I can simply call vite(['app','resource','bla']).

Gotcha, so you would run `vite(['resources/css/app.css', 'resources/js/app.js'])` and expect back `array('build/app.css?v=123123', 'build/app.js?v=123123')` or something similar?

**Comment by zaghadon** [comment]
Exactly, yeah.

**Comment by chrispage1** [comment]
> Exactly, yeah.

That makes sense - I'll get something worked up!

**Comment by chrispage1** [comment]
Hi @zaghadon 

This has now been added as of version 1.6.0

Any feedback is welcome 👍
