### ISSUE TITLE
Vite helper is returning vite URL, defeating the purpose

### ISSUE THREAD

**Issue by kirkbushell** [motomedialab/laravel-vite-helper#14]
I'm trying to use the CSS Inliner package for laravel, to generate emails. This package simply does not work as it's trying to load the style locations from Vite - which is impossible.

This package I was hoping would fix it, but it seems to do the following:

```php
dd(vite('resources/css/email.css', 'build', true))
```

Results in:

http://[::1]:5173/resources/css/email.css - an inaccessible file from the server. I just need to fetch the built file.

**Comment by kirkbushell** [comment]
Aha, turns out if you have the dev server running you're gonna have issues - shut down npm run dev, after you've built your files and you should be good to go.

**Comment by chrispage1** [comment]
> Aha, turns out if you have the dev server running you're gonna have issues - shut down npm run dev, after you've built your files and you should be good to go.

You got It! If you want to force bypass the hot server / dev you can run `vite('asset.css', hotServer: false)`. Hope that helps!
