### ISSUE TITLE
This doesn't work on production

### ISSUE THREAD

**Issue by kirkbushell** [motomedialab/laravel-vite-helper#15]
When trying to use the vite helper to grab the public path of a build file, it fails, with the following error:

In LaravelViteHelper.php line 34:
                                                   
  Unknown Vite entrypoint resources/css/email.css  

This is how I'm using it:

```php
public_path(vite('resources/css/email.css', 'build', true))
```

**Comment by chrispage1** [comment]
Hi @kirkbushell 

I take it you've run npm run build? Would you be able to send me your manifest file from `public/build/manifest.json`?

Also your Vite configuration file would be handy.

Thanks!

**Comment by chrispage1** [comment]
Hi @kirkbushell 

I have been unable to replicate this issue so unless you're able to provide more details.

Perhaps you're calling this before you have built the assets and don't have the hot server running?

If it's inside your logic, you can always wrap it in a try/catch to prevent a full failure if you're assets aren't compiled.

For now I'll close this but feel free to get back to me!

**Comment by kirkbushell** [comment]
Thanks, @chrispage1 - I had built the files, so I wasn't sure what was going on, but it appears to be working now, so I have no idea. Happy to close.

**Comment by chrispage1** [comment]
👍🏻 glad you got it sorted!

Thanks,
Chris.
