### ISSUE TITLE
Respect `withoutVite`

### ISSUE THREAD

**Issue by vilbergs** [motomedialab/laravel-vite-helper#6]
Hello!

Thank you for making this helper. I ran into some troubles when testing and wanted to suggest a feature (that I'm not smart enough to implement).

**Background**

We have some tests that assert that views are rendered, or at least contain certain HTML code. Before we used `$this->withoutMix()` in our test setup and this seemed to make sure that the `mix()` directive ran safely.

There is a `$this->withoutVite` equivalent, but I've had to mock the `vite` helper myself.

**Desired change**

It would be really cool if the `vite()` helper could somehow detect that `$this-withoutVite()` is active and return a dummy path on all calls to it, or just the path to the unbuilt resource.

Below you'll find the mock that I used to solve the problem for now:

```php
$viteHelperMock = $this->mock(LaravelViteHelper::class, function (MockInterface $mock) {
    $mock->shouldReceive('resourceUrl')->andReturn('/some-path');
});

$this->app->instance('vite', $viteHelperMock);
```

**Comment by chrispage1** [comment]
@vilbergs thanks for your input - the `withoutMix` helper is very useful but baked into Laravel's test suite itself. I'll have a look at writing up a trait for test suites so you can `use HasViteTests` or something along those lines.

**Comment by chrispage1** [comment]
@vilbergs I've written a trait for this that you'll be able to utilise as per the example - https://github.com/motomedialab/laravel-vite-helper#mocking-in-your-own-tests

Enjoy!

**Comment by vilbergs** [comment]
@chrispage1 Awesome. Thanks for taking the time to work on this!
